# 填QQ号。
# 为安全考虑，配置文件都只允许服务器主机本地修改，并且必须重启。
# 权限组应当与mc-commands.yml文件中的分组一一对应。

# 注意，权限组从上到下覆盖（例：用户114514同时位于architect和police内，则将会被识别为architect权限。）
# 如果需要给某些人分配跨组权限，请新建一个专门的组，并将此人分配到该组。

# 正规OP，默认给所有服务器可执行的指令权限（除了stop）
op:
    - 1234567

# 建筑师  例：给fill相关指令
architect:
    - 114514

# 警探  例：给ledger i相关指令
police:
    - 1919810

# 人事官  例：给whitelist、ban相关指令
HR:
